# Generated by Django 3.0.5 on 2020-06-01 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addresses',
            fields=[
                ('address_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('address1', models.CharField(max_length=40)),
                ('address2', models.CharField(blank=True, max_length=40, null=True)),
                ('city', models.CharField(max_length=40)),
                ('postal_code', models.CharField(blank=True, max_length=12, null=True)),
                ('state_province', models.CharField(max_length=40)),
                ('country_id', models.CharField(max_length=2)),
                ('longitude', models.BigIntegerField(blank=True, null=True)),
                ('latitude', models.BigIntegerField(blank=True, null=True)),
                ('created_by', models.CharField(max_length=60)),
                ('creation_date', models.DateTimeField()),
                ('last_updated_by', models.CharField(max_length=60)),
                ('last_update_date', models.DateTimeField()),
                ('object_version_id', models.BigIntegerField()),
            ],
            options={
                'db_table': 'addresses',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AvailableLanguages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=250)),
                ('creation_date', models.DateTimeField()),
                ('last_update_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'available_languages',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MembershipsBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_type_code', models.CharField(max_length=250)),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_update_date', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'memberships_base',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='statussupliers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=120)),
                ('supplier_status', models.CharField(max_length=30)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('ui_skin', models.CharField(blank=True, max_length=60, null=True)),
                ('creation_date', models.DateTimeField()),
                ('last_update_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'suppliers',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CountryCodes',
            fields=[
                ('iso_country_code', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('country_name', models.CharField(blank=True, max_length=100, null=True)),
                ('language', models.CharField(max_length=30)),
                ('source_lang', models.CharField(blank=True, max_length=30, null=True)),
                ('created_by', models.CharField(max_length=60)),
                ('creation_date', models.DateTimeField()),
                ('last_updated_by', models.CharField(max_length=60)),
                ('last_update_date', models.DateTimeField()),
                ('object_version_id', models.BigIntegerField()),
            ],
            options={
                'db_table': 'country_codes',
                'managed': True,
                'unique_together': {('iso_country_code', 'language')},
            },
        ),
        migrations.CreateModel(
            name='Persons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('registered_date', models.DateTimeField(blank=True, null=True)),
                ('email', models.EmailField(db_index=True, max_length=250, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('mobile_phone_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('credit_limit', models.FloatField(blank=True, null=True)),
                ('date_of_birth', models.DateTimeField(blank=True, null=True)),
                ('marital_status_code', models.CharField(blank=True, max_length=30, null=True)),
                ('gender', models.CharField(blank=True, max_length=1, null=True)),
                ('approximate_income', models.BigIntegerField(blank=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(max_length=250, unique=True)),
                ('last_update_date', models.DateTimeField(auto_now=True, null=True, verbose_name='last login ')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='onlineapp.MembershipsBase')),
                ('primary_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='onlineapp.Addresses')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
