# Generated by Django 3.0.5 on 2020-06-01 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlineapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persons',
            name='membership',
        ),
        migrations.RemoveField(
            model_name='persons',
            name='primary_address',
        ),
    ]
