# Generated by Django 3.0.5 on 2020-06-01 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineapp', '0002_auto_20200601_2054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membershipsbase',
            name='id',
        ),
        migrations.AddField(
            model_name='membershipsbase',
            name='membership_id',
            field=models.AutoField(auto_created=True, db_index=True, default=1, editable=False, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
