# Generated by Django 3.0.5 on 2020-05-29 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineapp', '0003_auto_20200527_1259'),
    ]

    operations = [
        migrations.CreateModel(
            name='statussupliers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=250)),
            ],
        ),
        migrations.RemoveField(
            model_name='persons',
            name='children_under_18',
        ),
        migrations.RemoveField(
            model_name='persons',
            name='confirmed_email',
        ),
        migrations.RemoveField(
            model_name='persons',
            name='contact_by_affilliates_flag',
        ),
        migrations.RemoveField(
            model_name='persons',
            name='contact_method_code',
        ),
        migrations.RemoveField(
            model_name='persons',
            name='contactable_flag',
        ),
        migrations.RemoveField(
            model_name='persons',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='persons',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='persons',
            name='object_version_id',
        ),
        migrations.RemoveField(
            model_name='persons',
            name='person_type_code',
        ),
        migrations.RemoveField(
            model_name='persons',
            name='principal_name',
        ),
        migrations.RemoveField(
            model_name='persons',
            name='provisioned_flag',
        ),
        migrations.RemoveField(
            model_name='persons',
            name='title',
        ),
        migrations.AddField(
            model_name='persons',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
